# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: async_pbrpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='async_pbrpc.proto',
  package='async_pbrpc',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x61sync_pbrpc.proto\x12\x0b\x61sync_pbrpc\"\x06\n\x04Void\"\n\n\x08NoReturnb\x06proto3')
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='async_pbrpc.Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=40,
)


_NORETURN = _descriptor.Descriptor(
  name='NoReturn',
  full_name='async_pbrpc.NoReturn',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=52,
)

DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['NoReturn'] = _NORETURN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), dict(
  DESCRIPTOR = _VOID,
  __module__ = 'async_pbrpc_pb2'
  # @@protoc_insertion_point(class_scope:async_pbrpc.Void)
  ))
_sym_db.RegisterMessage(Void)

NoReturn = _reflection.GeneratedProtocolMessageType('NoReturn', (_message.Message,), dict(
  DESCRIPTOR = _NORETURN,
  __module__ = 'async_pbrpc_pb2'
  # @@protoc_insertion_point(class_scope:async_pbrpc.NoReturn)
  ))
_sym_db.RegisterMessage(NoReturn)


# @@protoc_insertion_point(module_scope)
