# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: services.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import async_pbrpc_pb2 as async__pbrpc__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='services.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0eservices.proto\x1a\x11\x61sync_pbrpc.proto\"\x1f\n\x0fGetNameResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\x0fSayHelloRequest\x12\r\n\x05hello\x18\x01 \x01(\t\"!\n\x10SayHelloResponse\x12\r\n\x05hello\x18\x01 \x01(\t2@\n\rClientService\x12/\n\x08get_name\x12\x11.async_pbrpc.Void\x1a\x10.GetNameResponse2A\n\rServerService\x12\x30\n\tsay_hello\x12\x10.SayHelloRequest\x1a\x11.SayHelloResponseb\x06proto3')
  ,
  dependencies=[async__pbrpc__pb2.DESCRIPTOR,])




_GETNAMERESPONSE = _descriptor.Descriptor(
  name='GetNameResponse',
  full_name='GetNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='GetNameResponse.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=68,
)


_SAYHELLOREQUEST = _descriptor.Descriptor(
  name='SayHelloRequest',
  full_name='SayHelloRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hello', full_name='SayHelloRequest.hello', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=102,
)


_SAYHELLORESPONSE = _descriptor.Descriptor(
  name='SayHelloResponse',
  full_name='SayHelloResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hello', full_name='SayHelloResponse.hello', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['GetNameResponse'] = _GETNAMERESPONSE
DESCRIPTOR.message_types_by_name['SayHelloRequest'] = _SAYHELLOREQUEST
DESCRIPTOR.message_types_by_name['SayHelloResponse'] = _SAYHELLORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetNameResponse = _reflection.GeneratedProtocolMessageType('GetNameResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETNAMERESPONSE,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:GetNameResponse)
  ))
_sym_db.RegisterMessage(GetNameResponse)

SayHelloRequest = _reflection.GeneratedProtocolMessageType('SayHelloRequest', (_message.Message,), dict(
  DESCRIPTOR = _SAYHELLOREQUEST,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:SayHelloRequest)
  ))
_sym_db.RegisterMessage(SayHelloRequest)

SayHelloResponse = _reflection.GeneratedProtocolMessageType('SayHelloResponse', (_message.Message,), dict(
  DESCRIPTOR = _SAYHELLORESPONSE,
  __module__ = 'services_pb2'
  # @@protoc_insertion_point(class_scope:SayHelloResponse)
  ))
_sym_db.RegisterMessage(SayHelloResponse)


# @@protoc_insertion_point(module_scope)
